// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ynjwmtokkcdaudsaqwxb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InluandtdG9ra2NkYXVkc2Fxd3hiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk0MjA0MzQsImV4cCI6MjA1NDk5NjQzNH0.XQI3rtmg9oSNPkfcR5JJgFPgyakxNf-jF7O_dZRFSKE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);